name: 'Jensen UP3'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  repository_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment 
      required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:unit
    - run: npm run test:integration
